apiVersion: v1
kind: Service
metadata:
  namespace: user-service
  labels:
    app: user-service
  name: user-service
spec:
  ports:
  
    - protocol: TCP
      port: 2333
      targetPort: 2333
   
   
  selector:
    app: user-service
  type: ClusterIP
